
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import ttk, Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import *
import sqlite3
import tkinter as tk

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Desktop\function\assets3\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("510x340")
window.configure(bg = "#FFC1ED")


canvas = Canvas(
    window,
    bg = "#FFC1ED",
    height = 340,
    width = 510,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    16.0,
    16.0,
    495.0,
    323.0,
    fill="#FFFCFC",
    outline="")

def back():
    window.destroy()
    import main_menu

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
back_button = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=back,
    relief="flat"
)
back_button.place(
    x=24.0,
    y=284.0,
    width=55.0,
    height=39.779876708984375
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    186.64285278320312,
    39.5,
    image=entry_image_1
)
findByAny = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
findByAny.place(
    x=34.9523811340332,
    y=28.0,
    width=303.38094329833984,
    height=21.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    423.0,
    303.5,
    image=entry_image_2
)
deleteID = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
deleteID.place(
    x=405.9523811340332,
    y=292.0,
    width=34.095237731933594,
    height=21.0
)

def find():
    canvas.delete('all')
    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
    16.0,
    16.0,
    495.0,
    323.0,
    fill="#FFFCFC",
    outline="")

    # Create a database or connect to one
    conn = sqlite3.connect('DsTuLanh.db')

    # Create cursor
    c = conn.cursor()

    # Query the database
    res = conn.execute("SELECT *,oid FROM addresses")
    records = res.fetchall()

    # Find by any information
    i = 1
    searchResult = False
    print_records = ''
    lst = []
    for record in records:
            for index in range(7):
                if str(record[index]) == str(findByAny.get()):
                    lst.append(record)
                    searchResult = True
    
    for record in lst:
        print_records += (str(i) + '/ ' + str(record[0]) + '   [ Origin: '  +  str(record[1]) +  ' - Capacity: ' + 
                                str(record[3]) + ' - Price: ' + str(record[4]) + ' - S.N: ' + str(record[6]) + ' ]\n')
        i += 1
                
    # Print on the screen
    if searchResult == True:
        if 'text_id' in globals():
            canvas.delete(text_id)
        text_id = canvas.create_text(
        31.0,
        55.0,
        anchor="nw",
        text=print_records,
        fill="#000000",
        font=("Impact", 15 * -1)
        )
    else:
        # Create secondary (or popup) window.
        secondary_window = tk.Toplevel()
        secondary_window.title("Error")
        secondary_window.config(width=200, height=100,bg = "#CB0092")
        text = 'NO DATA'
        T = Text(secondary_window, height = 1, width = 7, font = ("Impact", 25 * -1))
        T.pack()
        T.insert(tk.END,text)

    findByAny.delete(0,END)
    
    # Commit Changes
    conn.commit()

    # Close Connection
    conn.close()
        
        

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
search_button = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=find,
    relief="flat"
)
search_button.place(
    x=359.0,
    y=20.0,
    width=128.0,
    height=38.33715057373047
)

def delete():
        # Create a database or connect to one
        conn = sqlite3.connect('DsTuLanh.db')

        # Create cursor
        c = conn.cursor

        # Query the database
        conn.execute("DELETE from addresses WHERE oid = " + deleteID.get())
        deleteID.delete(0,END)

        # Commit Changes
        conn.commit()

        # Close Connection
        conn.close()



button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))



delete_button = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=delete,
    relief="flat"
)
delete_button.place(
    x=457.0,
    y=289.0,
    width=30.0,
    height=30.0
)
window.resizable(False, False)
window.mainloop()
